/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RunnersIdImport } from './routes/runners/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RunnersIdRoute = RunnersIdImport.update({
  id: '/runners/$id',
  path: '/runners/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/runners/$id': {
      id: '/runners/$id'
      path: '/runners/$id'
      fullPath: '/runners/$id'
      preLoaderRoute: typeof RunnersIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runners/$id': typeof RunnersIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runners/$id': typeof RunnersIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/runners/$id': typeof RunnersIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/runners/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/runners/$id'
  id: '__root__' | '/' | '/runners/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunnersIdRoute: typeof RunnersIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunnersIdRoute: RunnersIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/runners/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/runners/$id": {
      "filePath": "runners/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
