/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RunnersIndexImport } from './routes/runners/index'
import { Route as JobsIndexImport } from './routes/jobs/index'
import { Route as RunnersIdImport } from './routes/runners/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RunnersIndexRoute = RunnersIndexImport.update({
  id: '/runners/',
  path: '/runners/',
  getParentRoute: () => rootRoute,
} as any)

const JobsIndexRoute = JobsIndexImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRoute,
} as any)

const RunnersIdRoute = RunnersIdImport.update({
  id: '/runners/$id',
  path: '/runners/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/runners/$id': {
      id: '/runners/$id'
      path: '/runners/$id'
      fullPath: '/runners/$id'
      preLoaderRoute: typeof RunnersIdImport
      parentRoute: typeof rootRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexImport
      parentRoute: typeof rootRoute
    }
    '/runners/': {
      id: '/runners/'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof RunnersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runners/$id': typeof RunnersIdRoute
  '/jobs': typeof JobsIndexRoute
  '/runners': typeof RunnersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runners/$id': typeof RunnersIdRoute
  '/jobs': typeof JobsIndexRoute
  '/runners': typeof RunnersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/runners/$id': typeof RunnersIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/runners/': typeof RunnersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/runners/$id' | '/jobs' | '/runners'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/runners/$id' | '/jobs' | '/runners'
  id: '__root__' | '/' | '/runners/$id' | '/jobs/' | '/runners/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunnersIdRoute: typeof RunnersIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  RunnersIndexRoute: typeof RunnersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunnersIdRoute: RunnersIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  RunnersIndexRoute: RunnersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/runners/$id",
        "/jobs/",
        "/runners/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/runners/$id": {
      "filePath": "runners/$id.tsx"
    },
    "/jobs/": {
      "filePath": "jobs/index.tsx"
    },
    "/runners/": {
      "filePath": "runners/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
